dexie/Dexie.js

src/Dexie.js

Usage: 
databaseExists("foo").then(AlreadyTaken, createDatabase)
Not sure if its a good idea to use reject like i do.
Maybe should be:
databaseExists("foo").then(function(result){
result ? AlreadyTaken() : createDatabase()
}, function(err){
console.log(err)
})

Added Dexie.exist

---

src/Dexie.js

If an immutable object is passed to `put` or `add`, trying to assign to the keypath will throw an exception. In that case, we should just not attempt to modify the object.

Don't try to modify frozen objects.

---

addons/Dexie.Observable/Dexie.Observable.js

Hi David, this pull request fixes very strange behaviour of syncable addon working with webservice protocol. Somehow not correct cleanup process does connect existing remote protocols (multiple times?) during db.open() and db.on('ready'), that finally deadlocks db opening. This bug was preventing me from using webservice sync protocol, however ajax protocol from your samples works just fine. I'm happy to nail down it after two days of debugging.
There are two more potentially wrong places, but since I'm not able to reproduce wrong behaviour I'm not touching that.
`readChanges(Observable.latestRevision[db.name]).then(cleanup).then(...)`
`db._syncNodes.update(nodeID, { deleteTimeStamp: 1, lastHeartBeat: 0 }).then(cleanup);`

fixing bug when sync starts when it shoul not and deadlocks the database

---

.gitignore
karma.conf.js
package.json
test/karma-env.js
test/tests-open.js

This adds ability to test Dexie.js from command line and opens a possibility of spinning up a CI.
For now, I only added core tests, addons test are hader to add because some of them are hardcoded into html files and we need to extract and maybe move them to `tests/addons` folder, so that `addons/` folder will only contain sources and dists.
I've chosen `mocha` reporter due to its readability, but we can discuss that.
Note that:
```javascript
"engines": {
"node": ">=4.2 <5.0"
},
```
is relevant only for potential CI env, not real platform support.

Enable testing with karma

---

src/Dexie.js
src/Promise.js
src/errors.js
test/tests-open.js

* Bugfix: DexieError.inner not present when it should
* Bugfix: Promises never return on node (when MissingAPIError was thrown)
* Feature: `new Dexie(name, {indexedDB: indexedDBImpl, IDBKeyRange: IDBKeyRangeImpl});` - possible to provide a backend API that Dexie will use instead of window.indexedDB and window.IDBKeyRange provided by the browser or IndexedDBShim.

Bugfixes + new options to Dexie constructor

---

src/Dexie.js
src/Promise.js
test/tests-collection.js
test/tests-exception-handling.js
test/tests-open.js
test/tests-promise.js
test/tests-transaction.js

Before, it was nescessary to always explicitely add a line like this somewhere in your bootstrapping code, or you could have issues debugging your code:
```js
Dexie.Promise.on('error', e => console.error(e))
```
But with this change, you don't need to do that anymore unless you'd like to show those errors somewhere else than in the console. Dexie.Promise will by default log any uncaught promise rejection. An exception from this rule is when you do stuff in a transaction scope. You never have to catch those operations but can instead catch the Promise that results from the transaction.
When writing this change, I noticed that Promise.on('error') was actually logging too much. Even though I was catching errors, the event subscriber would sometimes be triggered anyway. So this issue had to …

By default, log to console.error if any Promise was uncaught.

---

.npmignore
addons/Dexie.Observable/package.json
addons/Dexie.Observable/src/Dexie.Observable.js
addons/Dexie.Syncable/package.json
addons/Dexie.Syncable/src/Dexie.Syncable.js
src/.eslintrc.json
src/Dexie.d.ts
src/Dexie.js
src/Events.js
src/Promise.js
src/chaining-functions.js
src/debug.js
src/errors.js
src/utils.js
test/dexie-unittest-utils.js
test/qunit.js
test/tests-collection.js
test/tests-crud-hooks.js
test/tests-exception-handling.js
test/tests-extendability.js
test/tests-misc.js
test/tests-open.js
test/tests-promise.js
test/tests-table.js
test/tests-transaction.js
test/tests-whereclause.js
test/tests-yield.js

The result of some weeks of refactoring.
The main issue was that Dexie.Promise were:
1. Executing then-handlers in long call stacks making it hard to debug when error occur
2. Uncaught rejections where not possible to detect if direct exceptions had occurred in the constructor of a Promise.
3. Dexie needed to adjust to these limitations of the Promise class - to manually catch direct exceptions and abort the transaction directly - which made large amounts of the Dexie code mysterious and hard to understand the reason behind.
I also took the chance to simplify lots of code in Dexie, like db.open() and runUpgraders(). Now you don't have to step on your toes when dealing with promises anymore.
Optimized Promise class as much as possible and made it support long asyncronic stacks when in …

Promise totally rewritten + Cleaner Dexie code

---

samples/electron/index.html
samples/electron/package.json

In web pages, long stacks are automatically turned on when served from localhost. But electron apps are served from file:///, and there's no way for Dexie to tell whether this is a production or development environment.
The sample shows how to force debug mode, which is really a good thing while developing your app.
Also updated dependency to latest dexie with support for long stacks.

Updated info on how to get long stack support when using Electron.

---

src/Dexie.js
test/tests-upgrading.js

It looks like Dexie doesn't remove the underlying IDB object store on upgrade unless an upgrader function runs. I updated the relevant test so it correctly identified that `store1` was still present in the backing IDB and updated the check that was causing the deletion to not occur.

Confirm table deletion

---

.travis.yml
test/karma.travis.conf.js

Browserstack requires encrypted username and key env vars. Travis won't inject encrypted env vars from foreign pull requests resulting in that all pull requests fails. Need to work around this by running unit test locally on the travis server for pull requests but keep browserstack tests for the master branch.

Make pull-requests build without browserstack

---

src/Dexie.js

forEach() keeps looping through storeNames even if you set parentTransaction to null. Causing an error undefined when we call parentTransaction.tables. Since there's no break in a forEach loop, we just add an additional null check for parentTransaction inside, causing res if the loop iterations to be no-ops.

When checking parentTrans compatibility, make sure parentTrans is not already null

---

addons/Dexie.Observable/src/Dexie.Observable.js
addons/Dexie.Syncable/test/tests-syncable.js
addons/Dexie.Syncable/test/tests-syncprovider.js
package.json
samples/typescript/src/app.ts
src/.eslintrc.json
src/Dexie.d.ts
src/Dexie.js
src/Promise.js
src/errors.js
src/promise-utils.js
src/utils.js
test/dexie-unittest-utils.js
test/karma.release.conf.js
test/karma.travis.conf.js
test/tests-all.js
test/tests-asyncawait.js
test/tests-exception-handling.js
test/tests-open.js
test/tests-promise.js
test/tests-transaction.js
test/tests-tranx.js
tools/build-utils.js

This pull request upgrades the master branch with all changes from the temporary branch next/v2.
News in version 2:
* Support for async / await in Typescript 2.0 and Angular2.
* Support for native async/await in Chrome and Edge
* Deprecation of Dexie.Promise.on('error'). Use the standard `window.addEventListener('unhandledrejection', callback)` instead.
* No need to use Dexie.Promise.all(). Just use Promise.all().
API Differencies:
* WriteableTable and WriteableCollection are gone and instead incorporated into Table and Collection.
* Promise.on('error') is deprecated and should be replaced with windowaddEventListener('unhandledrejection')

Incorporate all from branch next/v2

---

addons/Dexie.Observable/src/Dexie.Observable.js
addons/Dexie.Syncable/test/tests-syncable.js
addons/Dexie.Syncable/test/tests-syncprovider.js
samples/typescript/src/app.ts
src/.eslintrc.json
src/Dexie.js
src/Promise.js
test/tests-exception-handling.js
test/tests-promise.js

* Support for window.addEventListener('unhandledrejection').
* Deprecation of Promise.on.error and db.on.error.

Support for standard 'unhandledrejection'

---

samples/typescript/README.md
samples/typescript/package.json
samples/typescript/src/app.html
samples/typescript/tsconfig.json
src/Dexie.d.ts

Running the 'typescript' sample in Dexie 2.0.0-beta.2 was only tested on IE, Edge, Chrome and Opera.
When tested on Firefox, it threw "InvalidStateError".
Reason for this is that babel's Promise shim seems to be incompatible with indexedDB on Firefox.
Now that Typescript 2.1 support direct transpilation towards ES5, there is no need to involve babel in the build process.

Resolving #350 - Typescript sample in 2.0.0-beta breaks on Firefox

---

src/utils.js
test/dexie-unittest-utils.js
test/tests-all.js
test/tests-asyncawait.js
test/tests-blobs.js

Support for intrinsic objects (Blobs, Typed arrays ect) in deepClone() so that they will be treated as primitive object and not be deeply cloned. Only deep clone custom objects.
Added unit tests for blob support. The first one succeeds (we had blob support already when not using hooks). But the second one failed before the fix.

Support blobs when hooks are involved

---

src/Dexie.js
src/Promise.js
test/tests-transaction.js

Inspired by @wwoods solution described  in #374 and the new [indexeddb-promises proposal](https://github.com/inexorabletash/indexeddb-promises/issues/11), I've added the method Dexie.waitFor() that may wait on a non-indexedDB Promise or Promise-returning function to complete and keep transaction alive during the whole lifetime of that task.
Implementation was also inspired by the elegant code in [polyfill.js](https://github.com/inexorabletash/indexeddb-promises/blob/master/polyfill.js) by @inexorabletash.

New tool: Dexie.waitFor() keeps transaction alive.

---

test/tests-upgrading.js

As discussed, here is a start towards some of the upgrade-related changes necessary to address #1, #105, and #287.
Still to do:

Upgrade fixes [in progress]

---

src/Dexie.d.ts
src/Promise.js
test/typings-test/test-typings.ts
test/typings-test/tsconfig.json

Added [Symbol.toStringTag] property to Promise.prototype (in js and d.ts).
Removed Promise.onuncatched from d.ts.
Added Promise.timeout in d.ts.

Resolves #389. Also update Promise interface.

---

src/.eslintrc.json
src/Dexie.js
test/tests-open.js

Dexie.getDatabaseNames() polyfills indexedDB.getDatabaseNames() for on non-chromium browsers. To do this, it adds the name of every opened table into a localStorage property. Silly not to use an indexedDB database? Reason may have been because I was allergic to storing meta-data in indexedDB. But it's actually even more ridiculous to store it in localStorage so I've moved it to use indexedDB (database '__dbnames') for recording database names so that the feature works in workers as well.
The code size went actually smaller with this change, so I think it's in the right path.
This change will automatically migrate existing localStorage data into the new __dbnames table.

Stop using localStorage for recording database names

---

addons/Dexie.Syncable/README.md

Fix typos.
Change wording of some sentences to make those more readable.
Fix where() call in the example to pass a string ('shoeSize') instead of
a variable.

Fixes in Dexie.Syncable README

---

addons/Dexie.Syncable/src/Dexie.Syncable.js

Update .mods of previousChange instead the clone of the previousChange object itself.
When the nextChange wanted to update a nested property which was already
set by the previousChange, then we tried to combine with the
previousChange directly instead of its mods.
When the nextChange wanted to update an object in which the
previousChange updated a nested property, we tried to delete the
previous property on the previousChange directly and not its mods.
See also: https://github.com/dfahlander/Dexie.js/issues/397#issuecomment-268009668
Unfortunately I didn't even manage to run the unit tests for Dexie.Syncable as `npm install` tried to install a Dexie version which was not available.

Fix combineUpdateAndUpdate function

---

samples/remote-sync/websocket/WebSocketSyncServer.js

Update .mods of clientChange instead of the clientChange object itself.
When resolving server and client UPDATEs we tried to remove the keyPath
from the clientChange object when there was a conflicting path instead of the
clientChange.mods object.
Similarly we tried to remove nested keyPaths which were in conflict from
the clientChange object instead of its .mods object.

Fix resolveConflicts function

---

addons/Dexie.Observable/src/Dexie.Observable.d.ts
addons/Dexie.Observable/src/Dexie.Observable.js
addons/Dexie.Syncable/src/Dexie.Syncable.js
addons/Dexie.Syncable/test/test-syncable-dexie-tests.html
src/Dexie.d.ts
src/Dexie.js
test/dexie-unittest-utils.js
test/tests-exception-handling.js

* Bug in rewritten Dexie.getDatabaseNames()
* Added missing properties to typings (d.ts) files of Dexie.d.ts and Dexie.Observable.d.ts.
* Dexie.Syncable: Correction of initial sync handling: 
* Don't await db.syncable.connect() to fulfill or reject each time the local database is opened. If DB has ever been synced with remote, we should rely on the offline state until connection is restablished. No need to halt queries while connecting.
* Very first time a database connects to a server, we MUST be online and wait for the connect to complete. Assume that the initial sync is essential for the application to function.
* Correction after running various unit tests for the addons:
* Make sure to never reopen a closed database by accident.
* Dexie.Syncable: Made 'url' index unique as it should …

Fixes 2016 12 21

---

addons/Dexie.Syncable/api.d.ts
addons/Dexie.Syncable/src/Dexie.Syncable.js
addons/Dexie.Syncable/src/connect-protocol.js
addons/Dexie.Syncable/src/get-local-changes-for-node/get-local-changes-for-node.js
addons/Dexie.Syncable/test/tests-syncable.js
addons/Dexie.Syncable/test/unit/get-local-changes-for-node/tests-get-changes-since-revision.js
addons/Dexie.Syncable/test/unit/get-local-changes-for-node/tests-get-local-changes-for-node.js
addons/Dexie.Syncable/test/unit/tests-register-sync-protocol.js
addons/Dexie.Syncable/test/unit/unit-tests-all.js

Until now Dexie.Syncable sent partial changes when we had more than 1000
changes. With the partialsThreshold property this can be configured
during protocol registration.
Only positive numbers are allowed and if no threshold is given, Infinity
is used. We use Infinity so that simple server implementations of the
protocol don't have to care about partial changes.
If partialsThreshold is 0, Dexie.Syncable will send no changes but will
always set partial to true. This can be used to only get server changes
and ignore any client changes.
Closes https://github.com/dfahlander/Dexie.js/issues/410

Make partials threshold configurable

---

samples/remote-sync/ajax/AjaxSyncProtocol.js

Fix some typos.
Add contentType property with application/json to the ajax call. Some
servers use it to know when to parse JSON.
Add warning that the needsResync flag is not implemented by
Dexie.Syncable.
Add partials flag to the server reply and pass it to
applyRemoteChanges().
When the server sends us a clientIdentity make sure we save it before
trying to resync. If saving failed we should stop syncing.

Fixes for the ajax sync protocol

---

src/Promise.js
src/utils.js

This fix the error "setImmediate is undefined" / "cannot call method 'bind' of undefined".
See https://github.com/dfahlander/Dexie.js/issues/485

Fix setImmediate call without qualifier

---

src/Dexie.d.ts

Dexie.exists() was non-static. Should be static. Dexie.delete() did only have the non-static db.delete() version. Not the static Dexie.delete(dbName).

Typings (d.ts) correction of Dexie.exists() and Dexie.delete()

---

src/Dexie.js

Fixes #323 
Rather than throwing `Unhandled rejection: AbortError: Transaction aborted` when the user is out of disk space, the underlying transaction error (`QuotaExceededError`) is bubbled up. This allows consumers of the Dexie API to identify `QuotaExceededError`s and handle them accordingly. 
NOTE: I used http://www.cylog.org/utilities/filldisk.jsp to fill up my hard disk to try this code locally.

bubble up `QuotaExceededError` instead of `AbortError: Transaction aborted`

---

src/Dexie.d.ts

Update Promise from this file https://github.com/Microsoft/TypeScript/blob/v2.1.4/src/lib/es2015.promise.d.ts because the current definition seems not compatible with typescript 2.3 PromiseLike definition.
For example :
```typescript
await Promise.all([dexiePromise1, dexiePromise2])
```
does not currently return the same type between typescript 2.2.2 and 2.3.1 without this change.

Update typescript Promise definition

---

package.json
test/is-idb-and-promise-compatible.js
test/tests-asyncawait.js
tools/build-configs/rollup.tests.config.js

Unit tests fails for Firefox 53. The unit tests that fails are those that test native async-await support. 
As described in #317, browser vendors (now only Firefox and Safari) still have incompatibility between their native Promise and their native IDBTransaction implementations. Dexie works around this by using its own Promise implementation, but when it comes to native async/await, we are totally in the hands of the native promise compatiblity. Chrome, Opera and Microsoft Edge have solved their previous incompatibility issues and they support both native async/await and Promise/IDB compatibility. Firefox used to lack both, but now they created the async/await support without solving the Idb/Promise incompatibility.
In summary, unit tests now do a feature test whether there is …

Firefox 53 supports async but still inconmpat w IDB!

---

src/Dexie.d.ts

According to the docs [here](http://dexie.org/docs/Dexie/Dexie.on.ready), `bSticky` is optional. It was causing TypeScript compiler errors when omitted, however.

Fix typing for .on('ready')

---

addons/Dexie.Syncable/src/apply-changes.js
addons/Dexie.Syncable/src/finally-commit-all-changes.js
addons/Dexie.Syncable/test/unit/tests-apply-changes.js

This pull request changes apply-changes to use a transaction to manage changes instead of using
chained promises.
This is to mitigate #569 as promises seem to behave badly in the presence of a large number (~18k) of changes.

Change apply-changes in Dexie.Syncable to use a transaction to manage changes instead of chained promises

---

src/Dexie.js

Workaround for Safari issue with getAll().

---

src/Dexie.js
src/utils.js
test/karma.browsers.matrix.js
test/karma.browserstack.js
test/tests-asyncawait.js
test/tests-misc.js
tools/release.sh

Resolves #230.
At last! This PR adds Iphone7/Safari 10.1 to the CI integration tests and pre-publish tests. There were 7 failing unit tests in Safari that has been fixed/worked around with this commit. To summarize them:
1. Objects retrieved from IDB seem to live in their own realm, so for example, it was not safe to check for (obj.dateColumn instanceof Date) as it is instance of the Date object in the foreign realm.
2. IDB/Promise compatibility: Native promises and IndexedDB actually plays ball in Safari, but you need to let IDB do the kick-off! As soon as a transaction has been created it has to be utilized before leaving the micro-tick. Some tests in native async/await support failed due to this limitation, but they could easlily be worked around by leading every transaction with a …

Include safari and smartphones in test suite

---

src/Dexie.js
test/tests-open.js

PR #579 was meant to work around a severe Safari issue with IDBObjectStore.getAll() that when called from a Web worker, results in a page crash followed by an automatic page reload. Since getAll() is just an optimization and not needed for IndexedDB to work, PR 579 shut down this optimization of utilizing on Safari. Due to the nature of the Safari bug (page crash + reload), feature testing was not possible - we could only do user-agent sniffing to avoid the bug.
The user-agent sniffing in PR  #579 did only look for "Safari" in user-agent, which made it also affect Chrome and Opera browsers (which was not the intent). Also, the bug has since been fixed in a later version of Safari + it only happened when called from a web worker, so we needed a more fine grained control of whether the …

Partially revert pr 579

---

src/functions/event-wrappers.ts
test/tests-crud-hooks.js

From #550:
> The bolded part leads one to believe that an updated object will be passed to the onsuccess handler, however, that does not appear to be the case.
Took a shot at fixing this instead of writing a buggy implementation of applyModificationsToObject to work around it. :-)
Also updated the 'updating' unit tests to verify it. Confirmed that updated tests fail without fix.
For anyone reviewing this, searching for `_hookCtx` reveals the relevant code that affects the execution of the code I changed. In particular, `Collection.modify` in collection.ts is the only one that sets `value`, and only when not deleting.
(I have not tested, though do expect, that when `modify` causes a deletion instead of an update, the updated object is not passed to the user's deletion `onsuccess` callback. …

Fix #550: onsuccess not passed updatedObj as documented

---

src/classes/version/schema-helpers.ts

Hi,
I recently encountered an exception where Dexie would try to access `navigator`, which was not available. I see that in the codebase it is usually checked that `navigator` is available before using, except in one place. So I added this check and it solves my issue.
I did not understand 100% the issue, but it seemed to happen while initializing a new version of a Dexie database with an extra table.
Cheers,
Rémi

Make sure navigator is available in our context before using it

---

package.json
src/public/index.d.ts
tools/append.js
tools/build-configs/export-default-dexie.txt

Hi there!
[I just released](https://github.com/timocov/dts-bundle-generator/releases/tag/v1.0.0) new version of `dts-bundle-generator` where I have fixed the bug when `export default` is removed from output - so you do not need to append it by yourself anymore 🙂 .
As soon `package-lock.json` is OS-dependent I am not sure how to update it right way. If you want - I can just push all changes made by my local `npm`.

Updated dts-bundle-generator

---

src/Dexie.js

Move the try statement up in order to cache invalid access of localStorage.
In 3.0, this whole last block of backward-compliant is removed. It is very non-cruzial. Was tempted to remove it in its whole in master-2 (2.x branch), but ... 2.0 is on maintainance and want to change as little as possible...

Resolve #617

---

package-lock.json
package.json

Sorry for 1.2.1 - it has accidentally merge commit which reverts back some changes (which should not be in the master) (see https://github.com/timocov/dts-bundle-generator/commit/02b8c38adcbe53a058f5ab71672c8b0f5bb8a855).
Now it works fine.

Update dts-bundle-generator to skip "broken" version (1.2.1)

---

src/classes/dexie/dexie.ts

The `delete()` method was using the global reference to `indexedDB` which both violates encapsulation and does not exist if you are using Dexie in node and injecting the indexedDB reference directly into its dependencies object.
Fix: Replace the global reference to `indexedDB` with a reference to the indexedDB database from the instance’s `_deps` property.
Note: this is currently not caught by the browser-based unit tests as this is not an issue that manifests in the browser.
Fixes #703

Fix Dexie delete database regression on Node.js

---

test/tests-collection.js

Instead of ok(), using equal() – which was the original intent. Not sure why the tests were passing in the browser but the number 2 in the method signature was expected to be a string by the ok() method.
Fixes dfahlander/Dexie.js#710

Update tests to fix str.replace is not a function error.

---

src/public/types/dexie.d.ts
test/typings-test/test-typings.ts

Also correcting the reality that current Transaction is given as argument to the scope function.

Solving issue 756 - able to use string as table args.

---

addons/dexie-export-import/src/export.ts

Following from https://github.com/dfahlander/Dexie.js/issues/777, this allows exports to continue without errors when tables are present but have no entries.

Nulled lastKey when table to export is empty.

---

src/functions/utils.ts
src/helpers/promise.js

I think this will meet requirements for #811. It is in 2 commits (which I would advise squashing if you accept pull request). I ran all tests with the 1st commit, and all passed. 
I think this is attaching the _global (ECMAScript) Promise high enough in the dependency chain that it is the native Promise implementation being added. I would assume if I was attaching the Dexie.promise at the wrong stage to the _global.Promise, the tests would fail after the 1st commit.
I also change template literal (back tick) to simple string as I think it is slightly more readable - I kept looking for the ${ insertion point, which wasn't there.
Thanks for creating this great library by the way.

ESNext compatibility

---

src/functions/utils.ts

Old browsers that do not have Promise on window seems to fail. Fixing by verifying typeof Promise === 'object' before applying the #812 workaround.

Fix #812 for IE11

---

src/functions/utils.ts

typeof Promise is either "undefined" or "function". In #813, it was checked for "object" which would probably never be true (functions used to be "object" in ES3 but then Promise did not exist)
Also added some comments explaining why this statement is there.
#812

Bugfix of previous PR - checking for typeof Promise==='function' instead of 'object'

---

addons/Dexie.Observable/test/unit/deep-equal.js
addons/Dexie.Observable/test/unit/hooks/tests-creating.js
addons/Dexie.Observable/test/unit/hooks/tests-deleting.js
addons/Dexie.Observable/test/unit/hooks/tests-updating.js
addons/Dexie.Observable/test/unit/tests-observable-misc.js
test/karma.browserstack.js

Safari returns objects from IndexedDB from another realm so QUnit's deepEqual() returns false also when the content is identical. Need a custom deepEqual() in some unit tests so that the tests pass.

Own deepEqual() required for Safari

---

src/dbcore/virtual-index-middleware.ts
test/tests-whereclause.js

VirtualIndex makes it possible to use the first part of a compound index as if it was an ordinary index.
DBCore will emulate an ordinary index so that it will works with algorithms such as equalsIgnoreCase() etc.

Bugfixes in virtual index.

---

addons/dexie-export-import/package-lock.json
addons/dexie-export-import/src/export.ts
addons/dexie-export-import/test/edge-cases.ts

- Added unit test for filtered chunked exports (#862)
- Fixed #862:
- exportAll@dexie/addons/dexie-export-impot/src/export.ts:
- Code now tracks the number of filtered rows
- Commas are now appended to table data only when the number of filtered rows in the last iteration is greater than 0
- All tests passing

Fix #862: Invalid JSON in Filtered Chunked Exports

---

src/public/types/where-clause.d.ts
test/typings-test/test-typings.ts

This fixes a syntax error when trying to call `WhereClause.anyOf()` with a compound key in TypeScript

Change typings to allow for compound keys

---

src/public/types/db-events.d.ts

(to accurately match what is provided runtime)
populate event is run when database is within an upgrade transaction for the inital creation of the schema.
Since Dexie has its own zone system, this given transaction argument does not need to be used, but we've also used the convention to provide the transaction instance to upgraders and this change matches that as populate is a special type of upgrader.

Expose transaction in populate event

---

package.json
src/classes/dexie/transaction-helpers.ts
src/classes/version/schema-helpers.ts
src/helpers/promise.d.ts
src/helpers/promise.js
test/run-unit-tests.html

Could find the native promise using crypto.subtle.digest instead.
Also: Not anymore relying on wether the callback to db.transaction() or .upgrade() is an async function or not. Always being prepared for async/await in any transaction instead.
Also: Taking hight for larger number of micro-awaits than before.

Resolves #722

---

addons/Dexie.Syncable/src/Dexie.Syncable.d.ts

@oppianmatt and @tunarob from my team found a mistake in type definitions of Dexie.Syncable addon: `disconnect` and `delete` are missing Promise return type.

Correct type definitions for syncable addon

---

addons/dexie-export-import/package-lock.json
addons/dexie-export-import/package.json

This PR affects dexie-export-import only.
Upgrade the bundled dependency clarinet to the version that includes my PR.
Bump version number. 
This version is already released on npm.

Upgraded clarinet

---

addons/Dexie.Syncable/api.d.ts
addons/Dexie.Syncable/src/Dexie.Syncable.d.ts

Fixes #944. Note that the [npm page](https://www.npmjs.com/package/dexie-syncable) contains the following snippet:
```
import Dexie from 'dexie';
import 'dexie-syncable'; // will import dexie-observable as well.
```
I am unclear on whether consumers need access to IDatabaseChange, but if so, dexie-observable will also need to be imported.

Import IDatabaseChange directly in Dexie.Syncable vs re-exporting from api

---

src/classes/collection/collection.ts

Iterate the failures array using for...of Object.keys() instead of for..in.

Fix for issue 947

---

src/classes/table/table.ts
src/public/types/table.d.ts
test/tests-table.js

See Issue: #969 
**Added code to support an options object on bulkAdd() and bulkPut() methods.**
These methods now accept an optional object on the second or third parameter. Instead of receiving only the last key it is now possible to use the, already implemented feature, to return all keys via { allKeys: true }:
_Example:_
`bulkAdd(someObject[], { allKeys: true })`
or
`bulkAdd(someObject[], someKey[], { allKeys: true })`
**Typings**
Also included improved typings for these methods. Via overloads, the correct return type (TKey | TKey[]) will be used.
**Tests**
Added test for the updated methods and some tests for backward compatibility (**no breaking changes**).
**Performance**
Did not add any performance tests (didn't know how and where you wanted them). I did some testing in my own …

Feature:  optionally all keys are returned on creating methods

---

addons/Dexie.Observable/src/on-storage.js

Dexie.Observable: Cannot read property 'indexOf' of null #791
https://github.com/dfahlander/Dexie.js/issues/791
>It is reacting to the "storage" event. When storage is cleared, it may not come with a key. A valid fix would be to null-check event.key.

null check key first

---

src/helpers/database-enumerator.ts

This PR will skip the use of the old, long time ago, deprecated webkitGetDatabaseNames() api and instead use the new chromium-supported indexedDB.databases() api to enumerate databases.

Use indexeddb.databases() and skip deprecated webkitDatabaseNames

---

src/classes/version/schema-helpers.ts
test/tests-table.js

It's a general issue if a table name collides with a property of Transaction. This PR reproduces the issue and has a generic fix for it. All the following table names did previously trigger the issue:
* db
* mode
* storeNames
* schema
* idbtrans
* on
* parent
* active
* _reculock
* _blockedFuncs
* _resolve
* _reject
* _waitingFor
* _waitingQueue
* _spinCount
* _completion
With this fix there should no more be any restrictions on table names.

Repro and fix issue 1039 - Table name "schema" not working in dexie 3

---

addons/Dexie.Observable/api.d.ts

This PR resolves #1057 by adding a few missing fields to the TS type definitions for the Dexie-Observable API.
The [Dexie documentat](https://dexie.org/docs/Observable/Dexie.Observable.DatabaseChange) declares that `DatabaseChange` objects should have `obj` and `oldObj` depending on the change type, as well as an optional `source` field. These fields are missing from the current Typescript definitions:
https://github.com/dfahlander/Dexie.js/blob/v3.0.1/addons/Dexie.Observable/api.d.ts

Adds missing fields to Dexie-Observable TS type definitions

---

src/classes/table/table.ts
test/tests-crud-hooks.js
test/tests-misc.js

Fire the reading hooks on the results of Table.bulkGet, as in Table.get.
This fixes the problem where Table.bulkGet results don't match Table.get results when Table.mapToClass is in effect. (mapToClass leverages the reading hook.)
Fixes #1079

Run reading hooks on Table.bulkGet

---

src/public/types/table.d.ts
test/typings-test/test-typings.ts

This improves the typing for Table.bulkGet() to indicate
the returned array may include undefined items.
(Per the [bulkGet docs][], "For those keys that do not
exist in the database, undefined will be returned in their
place.")
[bulkGet docs]: https://dexie.org/docs/Table/Table.bulkGet()

Fix Table.bulkGet return typing to include undefined

---

src/public/types/table.d.ts

Closes #1105 
@dfahlander You mentioned that it's going to be a tsc error, but seemingly the build and tests all pass without any errors.

#1105 Allow readonly arrays for bulk put & get methods

---

src/classes/dexie/dexie-open.ts
src/classes/version/schema-helpers.ts
src/functions/utils.ts
test/tests-misc.js
test/tests-upgrading.js

Warn on console in the case that the schema is altered without a version increment.
Don't fail, because this could destroy prod environments that works despite a faulty schema.
Warn unconditionally no matter the value of Dexie.debug. This is an important warning and it can be easily fixed by the user - just increment version number passed to db.version(...).

Verify schema on open

---

src/errors/errors.d.ts
src/public/types/dexie-constructor.d.ts

Hello,
I tried to check dexie error name in my typescript project next way:
```
} catch (err) {
switch (err.name) {
case Dexie.errnames.Constraint:
console.log('already exist')
break
default:
console.log('other error')
}
}
```
And I have the next error:
```
Property 'Constraint' does not exist on type '{ OpenFailedError: "OpenFailedError"; VersionChangeError: "VersionChangeError"; SchemaError: "SchemaError"; UpgradeError: "UpgradeError"; InvalidTableError: "InvalidTableError"; ... 24 more ...; BulkError: "BulkError"; }'.
```
I think it's because you use values of error names as keys
But I'm new to TS so I may be wrong
Thanks!

use error keys insted of values for typescript

---

test/tests-table.js

This is a small unit test cleanup discovered during preparation of an unrelated pull request.
One of the `Table` unit tests uses an `updating` hook to make assertions on the expected behaviour, but does not remove the hook after the unit test completes.
This cleanup ensures that the hook is removed, so that it doesn't run and apply assertions for any subsequent/unrelated unit tests.

Cleanup: ensure db.folks update hook is removed after unit test completion

---

src/classes/version/schema-helpers.ts

Due to how @babel/plugin-transform-typescript transpiles class fields, we had to change the Typescript recommendation of how to subclass Dexie. This commit makes it possible to go back to the previous recommendation in the docs - do only declare the classes and not have to manually initialize the tables in the constructor.
Plan: Wait with the docs updates until this commit has been released and then for another while until enough people have upgraded their Dexie to that version.
The docs should then be updated to propose a plain declaration of table properties, with an exclamation mark to hint about that the field is there despite not being assigned to in the constructor.
```ts
class MyAppDatabase extends Dexie {
contacts: Dexie.Table<IContact, number>; // number = type of the primkey …
```

Allow declaration-only tables for TS users.

---

addons/Dexie.Observable/src/Dexie.Observable.js

The cause of #1126 seems to relate to conflict between the (re)use of transactions on the `_syncNodes` Dexie-internal table after the `ready` trigger fires but before the database has completed opening.
The attempted fix here replaces two separate read & then write operations with a single-pass `modify` operation over the `db._syncNodes` internal table -- relying on [`Table.orderBy`](https://dexie.org/docs/Table/Table.orderBy()) to ensure that existing master sync node state is assessed before the 'local'  sync node record is updated -- within a  [`Dexie.ignoreTransaction`](https://dexie.org/docs/Dexie/Dexie.ignoreTransaction()) -- to retain atomicity, while avoiding re-use of the 'current' transaction.
Resolves #1126

Dexie.Observable: startObserving function: remove read-only query in order to avoid TransactionInactiveError

---

src/classes/version/schema-helpers.ts

The .src property is treated as being different if using dexie-observable's '$$' prefix, resulting in error when upgrading never works if using it.
Resolves issue #1148

Don't compare .src property of the primary index.

---

src/classes/where-clause/where-clause.ts
test/tests-whereclause.js

In Dexie 3.0.0-3.0.2, WhereClause.equals(undefined) does not fail but instead returns all results order by the given field.
This is a regression as it did fail in Dexie 2.x.

Issue1154: WhereClause.equals(undefined) should fail

---

src/classes/dexie/dexie-open.ts
src/classes/dexie/dexie-static-props.ts
src/classes/dexie/dexie.ts
src/helpers/database-enumerator.ts
src/index.ts
test/tests-asyncawait.js

A lighter implementation of PR #820.
* Regard each indexedDB dependency as it's own "world".
* Switching Dexie.dependencies.indexedDB to another implementation should enumerate databases there and not regard databases created elsewhere to listed there.
* Creating a Dexie instance with {indexedDB, IDBKeyRange} set in options should act in that "world" if database is created or deleted.
Hopefully everything from PR #820 is included in this PR. I wanted to implement it more lightway without the need of classes as that could add unnescessary size to dexie.min.js. Hopefully this implementation is also easy to understand.
Note: The case when indexedDB isn't present or is behind a security policy was previously covered by a try...catch in initializeDbEnumerator() and checked for undefined …

dbName follows dependencies.indexedDB (II)

---

src/functions/utils.ts
test/tests-crud-hooks.js

When diffing 2 objects, treat array properties as intrinsic objects and never go into them to treat array indices as if they were object props.
Resolves #1195.

Never treat array properties as delta-objects in update hook

---

src/classes/table/table.ts
src/errors/errors.js
src/public/types/errors.d.ts
test/tests-table.js

BulkError: Add failuresByPos property

---

src/classes/dexie/dexie-open.ts
src/classes/dexie/dexie.ts
src/public/types/db-events.d.ts

Add the close event to the DbEvents list, so close event can be subscribed by doing this,
db.on('close'). This close event only fires if the database is unexpectedly closed.

Expose close event

---

package.json

Extremely minor; reduces HTTP redirects during sessions that open the link.  A lot of NPM packages seem to link to their homepages via HTTPS (this is visible when using some of the NPM CLI tools), so this stood out and looks like a small change.

Update package homepage link proto (HTTP to HTTPS)

---

src/live-query/observability-middleware.ts
test/tests-live-query.js

...as reopen reason for 1225 is - a special case that only seem to happen on outbound tables and bulk putting/adding >= 50 items and the query is a range that is open in one of its ends (like above()).

Issue1225 again: liveQuery() fails to react on >50 bulk requests if previous resultset was empty

---

src/functions/utils.ts

Add FileSystemFileHandle to the list of intrinsic type names - so that object cloning works for FileSystemFilehandles.

Support for FileSystemFileHandle when cloning

---

src/classes/transaction/transaction.ts

Resolves issue with Transaction.abort() did not abort the transaction.
Reason was that Transaction.abort() set this.active to false, and rejected the promise. When promise rejection was catched, it should do the actual abort but it didnt to so because of the active state was already set to false by Transaction.abort().

Resolves issue reproduced in PR #1329

---

test/tests-transaction.js

I've written a test to demonstrate. The documentation [here](https://dexie.org/docs/Transaction/Transaction.abort()) states that abort `// Will discard all changes`, but it doesn't seem to for me. I ran this is chrome.

Transaction.abort does not rollback changes

---

src/classes/dexie/dexie-dom-dependencies.ts
src/classes/dexie/dexie-static-props.ts
src/classes/version/schema-helpers.ts
src/functions/get-object-diff.ts
src/functions/utils.ts
src/globals/global.ts
src/helpers/promise.js
src/hooks/hooks-middleware.ts
test/tests-crud-hooks.js
test/tests-table.js

This PR resolves #1720 by simplifying getObjectDiff a bit. Keeping the other current behaviour of diffing nested POJO objects but treating array properties and other exotic types as always diffing.
This PR replaces #1272.

Resolve issue 1270

---

src/classes/collection/collection.ts
src/classes/dexie/dexie-open.ts
src/classes/dexie/dexie-static-props.ts
src/classes/observable/observable.ts
src/classes/transaction/transaction.ts
src/classes/version/version.ts
src/dbcore/virtual-index-middleware.ts
src/functions/utils.ts
src/live-query/enable-broadcast.ts
src/public/types/db-events.d.ts
src/public/types/dbcore.d.ts
src/public/types/observable.d.ts

A few changes:
Before, we didn't call DBCore.transaction() internally to allow middlewares to intercept transaction creation. This PR corrects that and also added a second argument for which tables / object stores to include in the transaction. This allows for DBCore middlewares to inject code into both implicit and explicit transactions.
DBCoreMutateRequest has been extended with optional parameters `criteria` and `changeSpec`. This allows for middlewares to understand the intent of the mutation (which range-query that was the criteria for the change, and which properties that is meant to be updated). For Dexie Cloud, this feature makes it possible perform consistent operations across peers and maintain offline consistency for range- or index based calls to Collection.modify() and …

Changes and bugfixes done during dexie-cloud development

---

addons/dexie-export-import/src/import.ts
addons/dexie-export-import/test/edge-cases.ts

Bugfix + unit test.
In this commit import clears all db tables if flag is provided. Or is it intended to clear only those tables which are being imported?

Bugfix: fix importInto clearTablesBeforeImport option (issue #1342)

---

src/classes/transaction/transaction.ts
src/globals/global-events.ts
src/live-query/enable-broadcast.ts
src/live-query/live-query.ts
src/live-query/propagate-locally.ts
src/public/types/db-events.d.ts

Official event Dexie.on('storagemutated').
This change is a step to making dexie@3.2.0 an officially supported stable release where the observability communication channel can be official and documented.
The event was previously undocumented and had the name Dexie.on('txcommitted'). The event is the channel that communicates changes on indexeddb databases to enable `liveQuery()` to detect changes across service worker, windows and tabs. Event is propagated across peers using BroadcastChannel on browsers supporting it, and "storage" event on IE and Safari.
Breaking Change of undocumented event name: The renaming of the event is a "breaking change" from previous beta versions (dexie@3.1.x-beta.x and dexie@3.2.x-beta.x) even thought the event hasn't been any part of the officially supported …

Official event Dexie.on('storagemutated')

---

src/classes/dexie/dexie.ts
src/classes/dexie/generate-middleware-stacks.ts
src/classes/version/schema-helpers.ts
src/classes/version/version-constructor.ts
src/classes/version/version.ts
src/public/types/dexie.d.ts

Make sure db calls during db.on('ready') doesn't block when using a modern build where async/await aren't transpiled and we therefore need to rely on the vip flag property (db._vip) instead of only relying on the scoped vip flag (PSD.vip).
Resolves #1484

Make dexie-cloud-addon modern build not block (vitejs use case)

---

src/classes/dexie/dexie.ts
src/classes/dexie/generate-middleware-stacks.ts
src/classes/version/schema-helpers.ts
src/classes/version/version-constructor.ts
src/classes/version/version.ts
src/public/types/dexie.d.ts

Revert "Make dexie-cloud-addon modern build not block (vitejs use case) (#1548)"
This reverts commit fa4330801c788ad411a3b94388c23c05df142e9c.
Turns out to generate PrematureCommitError. Need to examine why and fix it before recreating a new version of #1548.

Revert PR1548

---

addons/dexie-cloud/package-lock.json
addons/dexie-cloud/package.json
addons/dexie-cloud/src/DexieCloudAPI.ts
addons/dexie-cloud/src/DexieCloudOptions.ts
addons/dexie-cloud/src/dexie-cloud-client.ts
addons/dexie-cloud/src/service-worker.ts
addons/dexie-cloud/src/sync/syncIfPossible.ts

Fix bug: dexieCloud addon did not work when used from within a service worker.
Observables were not setup correctly.
This PR also adds one new option to db.cloud.configure(): `{ disableWebSocket: boolean }`. By setting it to true, no websocket connection will be started by this instance of the db.

Fix bug: Using dexie-cloud from Service Worker

---

src/live-query/enable-broadcast.ts

A bugfix that ensures that importing Dexie.js in Node.js does not prevent the process from finishing. This is mostly relevant when Dexie.js is used in Node.js for unit tests.
Described problem without the fix: https://github.com/dexie/Dexie.js/pull/1576
Docs for the used `unref()` method:
https://nodejs.org/api/worker_threads.html#broadcastchannelunref

FIX #1576 Node.js process not exiting when Dexie.js is imported

---

src/functions/utils.ts

Same issue mentioned in #1236 exists for `FileSystemDirectoryHandle`s as well

Support for FileSystemDirectoryHandle when cloning

---

CONTRIBUTING.md
addons/Dexie.Observable/README.md
addons/Dexie.Observable/dist/README.md
addons/Dexie.Observable/package.json
addons/Dexie.Observable/src/Dexie.Observable.d.ts
addons/Dexie.Observable/test/unit/tests-observable-misc.js
addons/Dexie.Syncable/README.md
addons/Dexie.Syncable/dist/README.md
addons/Dexie.Syncable/package.json
addons/dexie-cloud/package.json
addons/dexie-export-import/README.md
addons/dexie-export-import/package.json
libs/dexie-react-hooks/package.json
package.json
samples/vue/README.md
test/tests-asyncawait.js

From https://github.com/dfahlander/Dexie.js to
https://github.com/dexie/Dexie.js
Tried to replace the urls where they makes sense. Some old code comments might not be correct anymore so I left them as-is for now and did not rewrite.

replace old repo URL to new one (dexie/Dexie.js)

---

src/public/types/table-hooks.d.ts

Hi.
Based on what I found writen in [docs](https://dexie.org/docs/Table/Table.hook('creating')) ...
>  // If returning any value other than undefined, the returned value will be used as primary key
... I feel like return type of `subscriber` param of `creating` table hook can be significantly improved.

feat(d.ts): type creating hook subscriber return value

---

addons/dexie-cloud/src/middlewares/createImplicitPropSetterMiddleware.ts
addons/dexie-cloud/src/middlewares/createMutationTrackingMiddleware.ts
src/classes/table/table.ts
src/errors/errors.js
src/public/types/dbcore.d.ts
src/public/types/table.d.ts
test/tests-table.js

In response to #632 a bulkUpdate is implemented that also preserves the intentions of the call (as already done in Table.update() and Collection.modify()) in case dexie-cloud is used (or other sync middleware that is interested of syncing indented operations and not just the actual ones, see https://dexie.org/cloud/docs/consistency#consistent-modify--and-delete-operations

Bulk update

---

addons/dexie-cloud/src/TSON.ts

Seems like the check for BigInt was running the BigInt() function, which is not available on iOS 13.7 e.g. Just checking if it's a function seems to do the trick.

Check BigInt availability without getting errors

---

addons/Dexie.Observable/package.json
addons/Dexie.Syncable/package.json
addons/dexie-cloud/package.json
addons/dexie-cloud/src/DexieCloudTable.ts
addons/dexie-cloud/src/extend-dexie-interface.ts
addons/dexie-export-import/package.json
libs/dexie-cloud-common/package.json
libs/dexie-react-hooks/package.json
package.json
pnpm-lock.yaml
src/public/index.d.ts
src/public/types/entity-table.d.ts
src/public/types/insert-type.d.ts
src/public/types/is-strictly-any.d.ts
src/public/types/table.d.ts
test/typings-test/test-extend-dexie.ts
test/typings-test/test-typings.ts

Revert to dexie@3.x style Table<T, TKey> but allow a 3rd optional parameter InsertType.
With inspiration from @nlaurie's PR's #1632 and #1635 and descriptions of the problems he faced with 4.0.0-alpha.4.
A complex type system can create hard-to-solve typing issues and trigger subtle bugs in the typescript compiler. It's also not good for backward compability with dexie@3.2.
TKey is now a plain key again, as in dexie 3.x.
To get the power from dexie@4.0.0-alpha.4's  Table<Entity, 'id'>: use the new generic EntityTable<T, PrimaryKeyProp>.
Using EntityTable instead of Table will opt-in to sugaring the InsertType by removing methods and making the primary key property optional in calls to table.add(), put(), bulkAdd(), bulkPut().
This is a suggestion for a solution of the problem discussed in …

Revert to dexie 3 style Table<T, TKey>

---

package.json

Fixes #326
Previously `//# sourceMappingUrl=...` wasn't appended to minified files.

Append sourceMappingUrl in minified files

---

import-wrapper-prod.d.mts
import-wrapper.d.mts

Right now, the current setup works in TypeScript but it's considered a bug and it should not be relied upon, see the thread and the comment [here](https://github.com/microsoft/TypeScript/issues/50762#issuecomment-1528318260). For that reason, I would like to fix all popular packages that misconfigured their `exports` this way so the bug can be fixed in TypeScript.
You can check the reported error [here](https://arethetypeswrong.github.io/?p=dexie%403.2.3)

Add `.d.mts` files to support `import` types properly

---

src/classes/observable/observable.ts
src/live-query/live-query.ts
src/public/types/observable.d.ts

Next version of dexie-react-hooks will optimize for liveQueries, given that the observable returned by liveQuery() has a `hasValue()` method returning false on initial render.
This PR adjusts liveQuery() in dexie@3 to supply the `hasValue()` method so that next version of dexie-react-hooks will stop firing of the initial dummy query on component render.
This PR also updates the typings of the Observable returned by liveQuery to the same typings as are returned in dexie@4.

Optimize live queries for useLiveQuery with dexie 3

---

src/live-query/cache/cache.ts
src/live-query/live-query.ts
src/live-query/propagate-locally.ts

Fixed the bug that mutations on foreign tabs and workers did not invalidate cache nor retrigger queriers when using cache and optimistic updates.

Fix broadcasted updates for cached queries

---

src/classes/dexie/dexie.ts
src/live-query/cache/cache-middleware.ts
src/live-query/live-query.ts
src/live-query/observability-middleware.ts

Fixes issues when middlewars on level 1 and above modify mutations.
Cache middleware were on level 10 which made them not able to compute optimistic updates based on the modified mutations but rather on the original mutations only because it cached values before those middlwares injected their values.
This issue affected some dexie-cloud users because liveQueries did not return the correct values of "owner" and "realmId" of added objects.

Move cache middleware to level 0

---

src/functions/utils.ts

Javascript is a bit unsuprisingly forgiving when passing array of string instead of a string:
```js
const obj = {id: 1};
obj.hasOwnProperty("id"); // returns true as expected.
obj.hasOwnProperty(["id"]); // Also returns true (!)
obj["id"] // returns 1 as expected.
obj[["id"]] // also returns 1 (!)
```
This commit makes sure to check typeof keyPath before passing it to getOwn() (alias for `(x, a) => Object.prototype.getOwnProperty.call(x, a))``

Bugfix: Support single-valued compound keys

---

addons/dexie-cloud/package.json
addons/dexie-cloud/src/authentication/interactWithUser.ts

To login as other user, the following format will be understood by the service: "yourEmail as targetEmail"
Example:
"david@dexie.org as foo@example.com"
Allow this format in the login dialog. Server will validate whether the first email owns an API client with GLOBAL_READ and GLOBAL_WRITE access. If so, OTP will be sent to owner email but token will be given out with the access for the second email.
This will help reproducting issues and troubleshooting. Note that this is not a secutiry concern - the first user has full control over the database and access to read and manipulate the full database via REST or import/export anyway. This is just a tool to be able to reproduce customer issues by logging in as them and follow repro steps.

Dexie Cloud: Allow DB owners impersonate users.

---

src/public/index.d.ts

Related issues: #1651 #1358 
With this change we can specify separate types for the get()/add() methods.
This avoids having to make the primary key optional which requires non-null checks/assertions
anywhere the result of get() is used.
```ts
class MyAppDatabase extends Dexie {
contacts!: Dexie.Table<IContact, number, Omit<IContact, 'id'>>; // <-- specify Insert type
constructor () {
super("MyAppDatabase");
this.version(1).stores({
contacts: '++id, first, last'
});
}
}
interface IContact {
id: number, // <-- not nullable anymore
first: string,
last: string
}
db.contacts.add({first, last}) // same as before
const contact = await db.contacts.get(1)
contact.id // <-- type is now number rather than number | undefined
```

Expose TInsertType of the Table interface

---

addons/dexie-cloud/src/DexieCloudAPI.ts
addons/dexie-cloud/src/authentication/authenticate.ts
addons/dexie-cloud/src/authentication/login.ts
addons/dexie-cloud/src/authentication/otpFetchTokenCallback.ts
libs/dexie-cloud-common/package.json
libs/dexie-cloud-common/src/types.ts

Extend the API of dexie-cloud-addon to support parameters `otp` and `otpId` to db.cloud.login(). This can be used when OTP message links to the application with otp and otpId in the query so that the application can use it and auto-login user using these two parameters.

Support magic links for OTP emails

---

src/index.ts
src/live-query/cache/signalSubscribers.ts
src/live-query/enable-broadcast.ts
src/live-query/obs-sets-overlap.ts
src/support-bfcache.ts

This pull-request addresses #1776.
It listens to pagehide and pageshow events.
pagehide:
* Stop BroadcastChannel
* Close all open Dexie instances into a state where they will auto-open next time a request comes in.
pageshow:
* Start BroadcastChannel to listen for live queries
* Fire off all liveQueries since we don't know which ones have been updated.

Support bfcache

---

src/functions/utils.ts
test/tests-misc.js

Table.update() corrupts values of type BigInt64Array.

Fix issue with BigInt64Array

---

addons/dexie-export-import/src/export.ts
addons/dexie-export-import/src/import.ts

In my effort to properly convert dexie-encrypted to work with more complex scenarios,  I found the need to completely exclude tables from the import export process.  Mainly the encryption metadata.  
So I added the options into the project both import and export,  to simply skip the requested list of tables in all operations.  
I feel this is a good addition to round out the options for controlling the backups. 
It's backwards compatible and does nothing if not specified. 
Regards
Nick

Added SkipTables Option

---

src/classes/dexie/dexie-open.ts
src/classes/dexie/dexie.ts
src/classes/version/schema-helpers.ts
src/functions/temp-transaction.ts
test/tests-misc.js
test/tests-upgrading.js

* Allow schema changes without version bump
* Allow downgrades
* Only require version bump when content upgrades are needed

Never throw VersionError

---

src/classes/dexie/dexie-open.ts
src/classes/table/table.ts
src/errors/errors.js
src/helpers/debug.ts
src/helpers/promise.js
test/dexie-unittest-utils.js
test/run-unit-tests.html

* Use Chrome's Async Task Tagging API to track failing operations down to the app code that initiated the operation.
* Fail fast on table.get(undefined)
* Remove old "long stacks" support that was tailored for older browsers and have no gain anymore.

Improve debugging experience

---

package.json
src/classes/dexie/transaction-helpers.ts
src/live-query/cache/apply-optimistic-ops.ts
src/live-query/cache/cache-middleware.ts
src/live-query/cache/signalSubscribers.ts
src/live-query/observability-middleware.ts
src/public/types/cache.d.ts
test/tests-live-query.js
tsconfig.json

Never let an 'rw' transaction leak information to live queries before the transaction commits. Even if liveQueries could benefit from optimistic updates, never let them through if they origin from an explicit 'rw' transaction. Instead let the liveQuery update when the 'rw' transaction commits. Still allow optimistic updates from "transactionless" operations such as `db.friends.update({name: 'Bar'})` without a transaction block around.
In normal situations, there's no much benefit from optimistic updates with IndexedDB since the transactions are fast and local anyway. However, in case a long-running transaction is locking the database, and you are showing an editable field component, it can be nice that the user updates are immediately propagated to the view no matter whether a transaction …

Avoid optimistic updates for explicit readwrite transactions

---

src/classes/collection/collection.ts
src/functions/replace-prefix.ts
src/helpers/prop-modification.ts
src/index.ts
src/public/index.d.ts
src/public/types/prop-modification.d.ts
src/public/types/update-spec.d.ts
test/deepEqual.js
test/tests-collection.js
test/tests-live-query.js
test/tsconfig.json
test/typings-test/test-typings.ts

Add a new class PropModification with capabilities of modifying properties into computed values based on the previous value, to improve the Operation-based CRDTs support that is already possible with where clauses and `Collection.modify()` but with more precise operations than just replacing a property to another constant value.
The first operation to support is `replacePrefix` that replaces the leading string of a string. This PR also exports a helper function `replacePrefix()` to use in modify operations that returns an instance of PropModification configured to do this operation. Future operations could include `increment` (for numbers), `push` (for arrays), `add` (for unique arrays / sets), `remove` for arrays, and `updateArrayItem` for arrays with object items.
The `replacePrefix` …

Allow advanced modifications of properties in Collection.modify

---

addons/dexie-cloud/src/dexie-cloud-client.ts
addons/dexie-cloud/src/sync/connectWebSocket.ts
addons/dexie-cloud/src/sync/messagesFromServerQueue.ts

An issue was reported privately that the following situation could occur:
1. Login prompt, enter email
2. OTP prompt enter OTP
3. Authentication happens
4. Sync starts
5. Web page is refreshed, aborting the sync call
6. Now, state could be authenticated but without any data from the realms that the user have access to - only from the public realm. Refreshing page again did not help. Only explicitely calling db.cloud.sync({purpuse: "pull"}) could resolve the state and download all data for the user.
The issue was that in connectWebSocket.ts, createObservable(), in case user is logged in, we're waiting with setting up the websocket until the user's sync call has completeted. Now if page was refreshed after login, but before sync call completed, the webSocket will wait there forever. We …

Issue login without sync

---

src/public/types/transaction.d.ts

Typescript complains that idbtrans does not exist, even if the class actually defines it:
```
$ cat src/classes/transaction/transaction.ts
…
/** Transaction
* 
* https://dexie.org/docs/Transaction/Transaction
* 
**/
export class Transaction implements ITransaction {
…
idbtrans: IDBTransaction;
…
```
This fixes this issue. Credit goes to https://stackoverflow.com/questions/78453173/typescript-pretents-foo-is-not-in-type-bar-while-it-is-how-to-debug/78453320#78453320

Fix missing idbtrans in transaction

---

package.json

Makes importing `dexie/dist/dexie.mjs` not restricted by package.json `exports` field.
Refs #1995

export ./dist/dexie.mjs

---

addons/Dexie.Syncable/package.json
import-wrapper-prod.mjs
import-wrapper.mjs
src/functions/propmods/add.ts
src/functions/propmods/index.ts
src/functions/propmods/remove.ts
src/functions/propmods/replace-prefix.ts
src/helpers/prop-modification.ts
src/index.ts
src/public/index.d.ts
src/public/types/prop-modification.d.ts
test/tests-collection.js

* number or bigint properties (add/subtract)
* array properties (treating array as a set)
```ts
import { add } from "dexie";
db.friends.update(1, {
age: add(1)
});
// Equivalent to:
db.friends.update(1, friend => ++friend.age);
// ...but works consistently in sync
```
```ts
import { add } from "dexie";
db.friends.update(1, {
interests: add(["football"])
});
// Equivalent to:
db.friends.update(1, friend => friend.interests = [...friend.interests, "football"].sort());
// ...but works consistently in sync
```
Checklist

CRDT for add/remove

---

addons/dexie-cloud/src/middlewares/createMutationTrackingMiddleware.ts
libs/dexie-cloud-common/package.json
libs/dexie-cloud-common/src/DBOperation.ts
src/classes/collection/collection.ts
src/public/types/dbcore.d.ts

When consistent modify/delete operations get chunked due to exceeding the default number of operations (200) in Collection.modify(), the additional chunks will now be flagged with with "isAdditionalChunk" so that consistent operations are never applied multiple times on the sync server.
We already make sure that if the where()...modify() operation results in zero matches locally, we still sync the operation to the server in case it would hit a result there, which could always be a possibility.
The thing we haven't taken care of is if the modify or delete operation resulted in multiple chunks into DBCore, resulting in multiple DBOperations synced to Dexie Cloud Server, the server did apply the condition and its updates multiple times. This is not an issue for idempotent operations such as …

Fix consistency for add()/remove() operations that are divided into chunks due to the number of rows being updated

---

package.json

followup on #1997, but now declaring the complete `dist` folder as `exports` in `package.json`, so that you can import `dexie/dist/modern/dexie.mjs` to without getting these rollup / vite errors:
```
[plugin node-resolve] Could not resolve import "dexie/dist/modern/dexie.mjs" in [...] using exports defined in [...]/node_modules/dexie/package.json.
```

add complete ./dist/* to package.json exports

---

addons/dexie-cloud/package.json
addons/dexie-cloud/src/DexieCloudOptions.ts
addons/dexie-cloud/src/dexie-cloud-client.ts

From customer request to support magic OTP links

requireAuth with options

---

src/helpers/rangeset.ts
src/live-query/cache/apply-optimistic-ops.ts
src/public/types/rangeset.d.ts
test/tests-live-query.js

Don't put multiple objects with duplicate primary keys into the liveQuery cache on bulkPut.

Resolve #2011 and #2012

---

src/live-query/cache/cache-middleware.ts

#2011 was another bug than #2012.
Its repro uses on.on('populate') to add objects.
Bug: The 'populate' event executes within 'versionchange' transaction and not normal 'readwrite' transaction.
Our cache is implemented using [Dexie.use()](https://dexie.org/docs/Dexie/Dexie.use()) middleware that overriders "transaction", "mutate" and "query".
The result was that our "mutate" override added the optimistic updates but the "transaction" override didn't follow up on these optimistic updates when the transaction settled because it only follows up on "readwrite" transactions so it left them hanging there forever.

Resolve 2011

---

pnpm-lock.yaml
src/classes/collection/collection.ts

Uses `cmp` for sortBy

---

src/classes/table/table.ts

This PR aims to fix issue #2064 
What I've changed is basically the comparison function, from idb.cmp() to cmp() defined at src/functions/cmp.ts

Cmp instead of idb

---

addons/dexie-export-import/package.json
addons/dexie-export-import/src/tson.ts
addons/dexie-export-import/test/basic-tests.ts
addons/dexie-export-import/test/tools.ts

Hello there, I'm the developer of [noto.ooo](https://noto.ooo/) and have been enjoying using Dexie and dexie-export-import as part of this project!
[I've **re-discovered a bug** that I believe surfaced in this pull request](https://github.com/dexie/Dexie.js/pull/1271).
With hopes of fixing this for my own project and to give a little back to this fantastic library I've done my best to put together the following pull request.
**Case:** When storing multiple Blobs with Dexie, exporting the database with dexie-export-import, then importing that exported database.
**Expected Behaviour:** I see each of my images displayed.
**Actual Behaviour:** I see the first of my many images repeated for as many images as there are.
I noticed this issue with a new feature I'm developing where images are …

Fix Multiple Image Blob Export

---

test/tests-live-query.js

In the unit tests for liveQuery, change how we wait until an expected result is emitted from a live query. Current tests were more prone to timing issues and race conditions. Now we instead do the following for those tests:
1. Define the expected results
2. Subscribe to live query and wait until the expected results arrive, or a timeout of 500 ms happens.
The thing is that liveQueries might emit a previous result at first, so by ignoring temporary outdated results we're not prone to timing issues except for the theoretical situtation that a liveQuery would take more than 500ms to emit expected result - which is practically irrellevant on the hardwares and queries we test.

Fix erratic livequery tests.

---

src/live-query/observability-middleware.ts

Bugfix: Resolution for #1946 was incorrect. This commit should solve it for good.

Resolution for #1946 was incorrect. This commit finally solves it.

---

src/classes/collection/collection.ts
src/public/types/dexie-constructor.d.ts

Single Database can have object stores with varying complexity and amount of data in them. Having one `modifyChunkSize` value may not be sufficient for all scenarios. 
This PR introduces an option to set `modifyChunkSize` per table.

Allow setting chunk size per table

---

libs/dexie-react-hooks/src/useLiveQuery.ts

When using dexie-react-hooks with TanStack Start (which uses Vinxi/Vite), the production build fails with the error "Named export 'Dexie' not found". This occurs due to an ESM/CommonJS interoperability issue in the production build process, while development mode works correctly.
The issue stems from how dexie-react-hooks imports Dexie and how Vite/Vinxi handles these imports in production mode. The current package configuration doesn't properly handle the dual ESM/CommonJS nature of the Dexie import when bundled in production.
Fixes: https://github.com/dexie/Dexie.js/issues/2153

Fix Named Export 'Dexie' Not Found in Production with Vite/Vinxi

---

libs/dexie-react-hooks/src/useDocument.ts
libs/dexie-react-hooks/src/usePermissions.ts

When using dexie-react-hooks with TanStack Start (which uses Vinxi/Vite), the production build fails with the error "Named export 'Dexie' not found". This occurs due to an ESM/CommonJS interoperability issue in the production build process, while development mode works correctly.

fix: 'Dexie' Not Found in Production with Vite/Vinxi dexie-react-hooks

---

addons/dexie-cloud/package.json
addons/dexie-cloud/src/sync/listClientChanges.ts

When multiple update operations have been done on the same property, don't send all updates but instead compute transactions that are entirely ovewritten by later transactions and only send the last one.
Must not be done if any update has a PropModification such as add/remove etc

Optimize sync updates

---

addons/dexie-cloud/src/middlewares/createMutationTrackingMiddleware.ts
libs/dexie-cloud-common/package.json
libs/dexie-cloud-common/src/DBOperation.ts
src/classes/collection/collection.ts
src/classes/table/table.ts
src/functions/apply-update-spec.ts
src/public/types/dbcore.d.ts
src/public/types/table.d.ts
test/tests-table.js

As prematurely documented on the website: https://dexie.org/docs/Table/Table.upsert()
We need this for realm creation on sharing. Recommendations of creating realms from boundRealmId will be updated in docs to use Table.upsert() instead of Table.put() - since Table.put() replaces the existing owner of the realm while Table.upsert() only makes sure to get the object created with some props but leaving owner property unchanged.

Feature: Table.upsert()
