dexie/Dexie.js

README.md
=> Add of NPM badge

src/Dexie.js
All test seem to pass, but you don't have any amd-specific tests, so I'm not sure about that.
Also probably need to re-genearate `Dexie.d.ts` and dist files (or that's will be done on release?)
Refers to https://github.com/dfahlander/Dexie.js/issues/125
=> Do not define name for require.js

README.md
Fix database name type in TypeScript example in Readme
=> Fix typo in database name in Typescript example in Readme

addons/Dexie.Observable/tools/build.js, addons/Dexie.Syncable/tools/build.js, package.json, samples/typescript/package.json, src/Dexie.js, test/karma.conf.js, test/tests-collection.js, tools/build.js
* Two bugs related to Collections. One new and one ancient.  …			08d4bc9
* Build script exit (1) on error and test using chrome instead of firef…  …			24ec5ce
=> Important bug fix + minor tools changes

src/Dexie.d.ts
=> Added BulkError to Dexie.d.ts

src/Dexie.js, src/utils.js, test/tests-misc.js, tools/release.sh
Fix of #248 'modifications' object in 'updating' hook can be bizarre.
=> Fix of #248

addons/Dexie.Syncable/test/tests-syncable.js, src/Dexie.js, src/Promise.js, test/tests-exception-handling.js
* Bugfix: Infinite loop with on.on('ready') (https://github.com/dfahlander/Dexie.js/commit/6f8ffd819a3d4bbaa7e948d5b763c6298341707f)
* Fixes due to deprecated db.on.error
* Support for window.onunhandledrejection
=> Various fixes

src/Dexie.d.ts, src/Dexie.js, test/tests-whereclause.js
let zlatan = await db.friends.get({email: "zlatan@ibrahimovic.se"});
let myself = await db.friends.get({firstName: "David", lastName: "Fahlander"});
let zlatans = await db.friends.where({firstName: "Zlatan", lastName: "Ibrahimovic"}).toArray();
let zlatan2s = await db.friends.where(["firstName", "lastName"]).equals("Zlatan", "Ibrahimovic").toArray();
db.friends.orderBy(["lastName", "firstName"]).toArray()
=> Support for pretty compound queries:

src/Dexie.js
If Promises are generated within a transaction scope but not awaited for, these promises were awaited for anyway by the transaction runner using Dexie-specific Promise.follow(). The idea behind this is if users don't code with a Promise-returning style, but just fire off promises without waiting for them or catching them, this should be OK as long as this is being done within a transaction. It can spare the user from having to call Promise.all([]) on everything, which is kind of nice.
However, there might be a risk that user fires off promises that should not be waited for. Specifically, this happens if using Promise.race(). Caller is only interested of waiting for the first promise that completes. So in that case, this behavior could be unwanted.
This commit disables this behavior in …
=> Prohibit idling on Promise.race() in transaction.

samples/typescript-simple/package.json
Listing all contributors that have made considerable contributions to Dexie.js. Thanks a lot for all contributions being made!
Did I miss a name? Please contact me or pull-request your name.
=> Added contributors to package.json

addons/Dexie.Syncable/test/karma.conf.js, addons/Dexie.Syncable/test/test-syncable.html, addons/Dexie.Syncable/test/tests-syncable-partials.js, addons/Dexie.Syncable/test/tests-syncable.js
Move the client partials tests out of tests-syncable and into
tests-syncable-partials (contains client/server partial tests for poll
synchronization).
Move the partialsThreshold test out of tests-syncable and into
tests-syncable-partials.
Add delete(url) test in tests-syncable.
Add server partials tests in tests-syncable-partials.
Add tests-syncable-partials to karma config and test-syncable.html.
=> Refactor Dexie.Syncable tests and add new ones

src/Dexie.js, test/tests-exception-handling.js, test/tests-upgrading.js, tools/build-utils.js
Reverts dfahlander/Dexie.js#395
=> Revert "Refactoring upgrade process"

addons/Dexie.Observable/package.json, addons/Dexie.Syncable/package.json, package.json
After renaming jsm to es.js, I forgot to update the module and jsnext:main attributes in package.json.
=> Oops. Package.json refers to wrong file

README.md, addons/Dexie.Observable/README.md, addons/Dexie.Syncable/README.md
This PR can be merged after https://github.com/dfahlander/dexie.js-web/pull/3
was merged
=> Point wiki links to docs on dexie.org

bower.json
From what I can tell, it looks like dexie.js is output to the dist folder and then minified from there, so this *should* work.
=> Fixed bower config to meet best practices (#488)

src/Dexie.js
=> Don't use IndexedDBShim just because it's included

src/Dexie.d.ts
=> Solving issue #512

addons/Dexie.Observable/README.md, addons/Dexie.Syncable/README.md
Inform the users of Dexie.Observable and Dexie.Syncable that they will
have to perform a schema upgrade for the addons to work properly.
Fix minor typo in Dexie.Syncable
Doc improvements based on dfahlander/Dexie.js#546 (comment)
=> Mention schema upgrade for existing DB

addons/Dexie.Observable/src/Dexie.Observable.d.ts, addons/Dexie.Observable/test/typings/test-typings.ts, addons/Dexie.Syncable/src/Dexie.Syncable.d.ts, addons/Dexie.Syncable/test/test-typings/test-typings.ts
As done in PR #568 but preserving the static API of the addons
=> fix typescript (type error) on adding addons

src/Promise.js
Trying to fix issue with zonejs 0.8.18 #589
=> Fixing incompability with zonejs 0.8.18

src/Dexie.js, src/Promise.js, src/utils.js
This helps with readability. Where Intellisense/autocomplete is
lacking, code can probably be simplified in the future.
Fixes #603.
=> Remove Intellisense helpers.

addons/Dexie.Observable/api.d.ts
Self explanatory little change, tested it locally and it works.
For more info:[](url) https://github.com/angular/angular-cli/issues/8068
=> Add const to enum in api.d.ts for better angular compatibility

src/classes/version/schema-helpers.ts, test/tests-upgrading.js
My attempt at making to-be-deleted stores still available via upgrader's transaction by specifically putting them back into a special upgrader schema. Not sure if this is the right approach but the added tests for shorter table rename and primary key change seem to pass with it.
=> Allow accessing to-be-deleted stores in upgraders (#105)

addons/Dexie.Observable/package-lock.json, addons/Dexie.Observable/package.json, addons/Dexie.Observable/tools/build-configs/rollup.config.js, addons/Dexie.Observable/tools/build-configs/rollup.tests.config.js, addons/Dexie.Observable/tools/build-configs/rollup.tests.unit.config.js
As some initial work for Dexie Observable updates (#606 has some mention of what I'm going to be working on here), I went ahead and updated the build deps of Dexie Observable. I have started working on fixing the TS definition but needed the build to work (and figured I'd touch it up while there and break out the commits for each feature/addition) first to test them.
=> Update build deps for Dexie Observable

src/helpers/promise.js, test/tests-misc.js
See https://github.com/dfahlander/Dexie.js/issues/729#issuecomment-435869252
=> Don't console.warn() unless Dexie.debug is truthy

test/tests-collection.js
Dexie 3 works around the issue now so it can be safely enabled.
Issue described in #594
=> Enabled an old unit test that used to fail on Safari.

src/classes/table/table.ts, src/public/types/table.d.ts, test/tests-table.js
=> Implementation of Table.bulkGet().

test/tests-table.js
when using hook("updating") date changes are not recognized as modifications.
=> extend issue #841 sample

addons/Dexie.Observable/package-lock.json, addons/Dexie.Syncable/package-lock.json, addons/dexie-export-import/package-lock.json, addons/dexie-export-import/package.json, package-lock.json, samples/react-redux/package-lock.json, samples/react-redux/package.json, samples/typescript-simple/package-lock.json, samples/typescript-simple/package.json
dexie-export-import 1.0.0-beta.13 released on npm.
This is the updated version numbers in package.json and package-lock.json
When merged, delete this branch!
=> Temp release dexie export import

src/classes/dexie/dexie.ts, src/classes/version/version-constructor.ts, src/classes/version/version.ts, test/tests-upgrading.js
Repro of #919.
Will use this PR to fix the issue as well.
=> Issue 919 versions decending order

src/classes/dexie/dexie-open.ts, src/classes/version/schema-helpers.ts
Mitigates the problem described in #942
=> Base schema upgrade on current schema information from the database

src/public/types/table.d.ts
Fix for PR #973 
See review from timbru31
=> fix: bulk methods now return PromiseExtended once again

src/classes/version/schema-helpers.ts, src/helpers/index-spec.ts, test/tests-upgrading.js
This PR is based on #984 and completes it.
=> Timbru31 fix/explicit unique primary key

src/helpers/promise.js
Related to #1037 AggregateError in src/helpers/promise.js
* Check existance of Promise.any and AggregateError before mimicing NativePromise.
* Don't polyfill Promise.any() - just support it if present.
=> Be more unobstrusive with Promise.allSettled and Promise.any

addons/Dexie.Observable/package-lock.json, addons/Dexie.Observable/package.json, addons/Dexie.Observable/src/Dexie.Observable.d.ts, addons/Dexie.Observable/src/Dexie.Observable.js, addons/Dexie.Observable/tools/build-configs/rollup.config.js, addons/Dexie.Syncable/package-lock.json, addons/Dexie.Syncable/package.json, addons/Dexie.Syncable/src/Dexie.Syncable.d.ts, addons/Dexie.Syncable/src/Dexie.Syncable.js, addons/Dexie.Syncable/tools/build-configs/rollup.config.js, addons/dexie-export-import/tools/build-configs/rollup.config.js
Fixes typings in dexie-observable and dexie-syncable to make them compatible with Dexie 3.0.
Resolves #1048 
Resolves #847
=> Issue 1048 addons for Dexie 3.0

src/classes/table/table.ts, src/functions/workaround-undefined-primkey.ts, test/tests-misc.js
=> Repro + resolve issue #1112: typescript declaration of id makes autoInc fail

src/helpers/promise.js
=> Keep incremented & decremented awaits in balance.

src/classes/collection/collection.ts, src/public/types/dexie-constructor.d.ts
This PR should resolve FR #1152.
Please give some feedback for the PR here or in #1152
=> Feature request: configurable chunk size for Collection.modify()

samples/vue/README.md
There seems to be an error in the command in the README. This patch should fix it.
=> Fix README of Vue + Dexie Todo Example

libs/dexie-react-hooks/package-lock.json, libs/dexie-react-hooks/package.json, libs/dexie-react-hooks/rollup.config.js
Switch to using rollup for dexie-react-hooks.
Still using webpack for the tests though.
=> As webpack fails to produce universal modules,

libs/dexie-react-hooks/package.json
Emitting type declaration files and declare module entry.
=> Resolve issue 1207 using rollup

src/classes/dexie/dexie-open.ts
Only put db value there if the database was created.
This commit may speed up the performance fiddle of bulkPut() referenced from dexie.org.
=> Don't put into _dbNamesDB on every open.

src/classes/version/version.ts, src/public/types/version.d.ts
=> Fix Version signatures

src/functions/utils.ts, src/helpers/rangeset.ts, src/public/index.d.ts, src/public/types/db-events.d.ts, src/public/types/rangeset.d.ts, test/rebalance.md, test/tests-all.js, test/tests-rangeset.js, test/tsconfig.json
Reproduction of issue 1268. TODO: Fix it!
=> Issue1268 live query crash

src/functions/utils.ts, src/functions/workaround-undefined-primkey.ts, test/tests-misc.js, test/tests-table.js
Based on PR #1283 but with adjustments.
Replaces PR #1283.
=> Seshrs fix/crypto key

addons/Dexie.Observable/src/Dexie.Observable.js
Trying to get dexie syncable round trip in https://blog.stackblitz.com/posts/introducing-webcontainers/
=> Check for global before checking its prop

src/public/types/table.d.ts
=> fix(bulk-delete): correctly define keys type

addons/Dexie.Observable/src/hooks/creating.js
=> Fix overriding createUUID()

samples/dexie-cloud-todo-app/README.md
Add the step about whitelisting origin from https://dexie.org/cloud/#getting-started
GitHub issue: #1540 / #1542
=> Small update to dexie-cloud-todo-app README

samples/dexie-cloud-todo-app/configure-app.sh, samples/dexie-cloud-todo-app/package.json, samples/dexie-cloud-todo-app/yarn.lock
(And bump the version of dexie-cloud-addon in the sample app)
=> Tiny update to the text in dexie-cloud-todo-app/configure-app.sh

samples/vue/README.md, samples/vue/babel.config.js, samples/vue/index.html, samples/vue/package-lock.json, samples/vue/package.json, samples/vue/src/components/AddTodo.vue, samples/vue/src/components/Todo.vue, samples/vue/src/components/TodoList.vue, samples/vue/vite.config.js, samples/vue/vue.config.js
refactor vue sample with vue3 composition api script setup syntax and vite.
=> refactor: vue sample

package.json
Add `sourceMappingUrl` to the v3 branch.
Cherry-picked from #1676
Fixes #326
=> #1676 for Dexie 3

src/classes/table/table.ts, test/tests-whereclause.js
Fixes #1740 for dexie@latest (3.x)
=> Fix #1740 for Dexie 3x

src/live-query/cache/apply-optimistic-ops.ts, test/tests-live-query.js
=> Resolving issue 1863

src/classes/table/table.ts
extremely minor grammar typo
... but my OCD tells me I have to !!
Thanks
=> Minor grammar typo

addons/dexie-export-import/package.json, addons/dexie-export-import/src/export.ts, addons/dexie-export-import/src/import.ts
=> Proposal for adding transform to export/import

src/helpers/promise.js
=> Promise.withResolvers
